
package com.web.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.4
 * Thu Apr 18 17:12:52 EDT 2013
 * Generated source version: 2.7.4
 */

@XmlRootElement(name = "sayHiResponse", namespace = "http://service.web.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sayHiResponse", namespace = "http://service.web.com/")

public class SayHiResponse {

    @XmlElement(name = "return")
    private java.lang.String _return;

    public java.lang.String getReturn() {
        return this._return;
    }

    public void setReturn(java.lang.String new_return)  {
        this._return = new_return;
    }

}

